package com.victorrendina.mvi.sample.list;

import android.support.annotation.Nullable;
import com.victorrendina.mvi.di.InjectableViewModelFactory;
import com.victorrendina.mvi.sample.data.EntityRepository;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;
import javax.inject.Provider;

// TODO This factory needs to be automatically generated by the @MviViewModel annotation
public class SampleListViewModelFactory implements InjectableViewModelFactory<SampleListViewModel, SampleListViewState, SampleListArgs> {

    private Provider<EntityRepository> repository;

    @Inject
    public SampleListViewModelFactory(
            Provider<EntityRepository> repository
    ) {
        this.repository = repository;
    }

    @NotNull
    @Override
    public SampleListViewModel create(@NotNull SampleListViewState initialState, @Nullable SampleListArgs arguments) {
        return new SampleListViewModel(initialState, arguments, repository.get());
    }
}
