package com.victorrendina.mvi.sample.counter;

import android.content.res.Resources;
import android.support.annotation.Nullable;
import com.victorrendina.mvi.di.InjectableViewModelFactory;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;
import javax.inject.Provider;

// TODO This factory needs to be automatically generated by the @MviViewModel annotation
public class CounterViewModelFactory implements InjectableViewModelFactory<CounterViewModel, CounterViewState, CounterArgs> {

    private Provider<Resources> resources;

    @Inject
    public CounterViewModelFactory(
            Provider<Resources> resources
    ) {
        this.resources = resources;
    }

    @NotNull
    @Override
    public CounterViewModel create(@NotNull CounterViewState initialState, @Nullable CounterArgs arguments) {
        return new CounterViewModel(initialState, arguments, resources.get());
    }
}
