package com.victorrendina.mvi.sample.fancylist;

import android.support.annotation.Nullable;
import com.victorrendina.mvi.MviArgs;
import com.victorrendina.mvi.di.InjectableViewModelFactory;
import org.jetbrains.annotations.NotNull;

import javax.inject.Inject;

// TODO This factory needs to be automatically generated by the @MviViewModel annotation
public class HomeListViewModelFactory implements InjectableViewModelFactory<HomeListViewModel, HomeListViewState, MviArgs> {

    @Inject
    public HomeListViewModelFactory(
    ) {
    }

    @NotNull
    @Override
    public HomeListViewModel create(@NotNull HomeListViewState initialState, @Nullable MviArgs arguments) {
        return new HomeListViewModel(initialState);
    }
}
